Repository QuokkaWallaby/Recorder-Frontend, pull requests merged in 2022-06, with the labels that each got.

#6 feat: 게시글 수정, 삭제(진행 중)
  frontend/src/App.js
  frontend/src/components/Editor/EditorBox.js
  frontend/src/pages/Editor.js
  frontend/src/pages/EditorUpdate.js
  frontend/src/pages/Post.js
  frontend/src/pages/User.js
  frontend/src/pages/Userhome.js
Labels: 🛠 리팩토링

#8 fix: main 정렬 오류 수정
  frontend/src/pages/Main.js
Labels: 📱 유아이, 🚐 핫픽스

#15 refact: 에디터박스 색상 수정
  frontend/src/components/Editor/index.css
Labels: 📱 유아이, 🛠 리팩토링
